# Generated by Django 4.2.7 on 2026-06-14 13:06

from django.db import migrations, models
import django.utils.timezone
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', '用户登录'), ('logout', '用户登出'), ('inbound', '入库提交'), ('outbound', '出库提交'), ('approve', '审批通过'), ('reject', '审批驳回'), ('execute', '执行操作'), ('delete', '删除记录'), ('create', '创建记录'), ('update', '更新记录'), ('archive', '日志归档')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(db_index=True, max_length=100, verbose_name='操作人')),
                ('target_object', models.CharField(blank=True, default='', max_length=200, verbose_name='操作对象')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('action_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='操作时间')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情JSON')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-action_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', '用户登录'), ('logout', '用户登出'), ('inbound', '入库提交'), ('outbound', '出库提交'), ('approve', '审批通过'), ('reject', '审批驳回'), ('execute', '执行操作'), ('delete', '删除记录'), ('create', '创建记录'), ('update', '更新记录'), ('archive', '日志归档')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(db_index=True, max_length=100, verbose_name='操作人')),
                ('target_object', models.CharField(blank=True, default='', max_length=200, verbose_name='操作对象')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('action_time', models.DateTimeField(db_index=True, verbose_name='操作时间')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情JSON')),
                ('archived_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='归档时间')),
            ],
            options={
                'verbose_name': '操作日志归档',
                'verbose_name_plural': '操作日志归档',
                'ordering': ['-action_time', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='goodsoutbound',
            name='outbound_no',
            field=models.CharField(default=warehouse.models.generate_outbound_no, max_length=30, unique=True, verbose_name='出库单号'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='transfer_no',
            field=models.CharField(default=warehouse.models.generate_transfer_no, max_length=30, unique=True, verbose_name='调拨单号'),
        ),
    ]
