from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('api/dashboard/kpi/', views.api_dashboard_kpi, name='api-dashboard-kpi'),
    path('api/dashboard/trend/', views.api_dashboard_trend, name='api-dashboard-trend'),
    path('api/dashboard/category/', views.api_dashboard_category, name='api-dashboard-category'),
    path('api/dashboard/activities/', views.api_dashboard_activities, name='api-dashboard-activities'),
    path('goods-entry/', views.menu_page, {'page_name': 'goods-entry'}, name='goods-entry'),
    path('unit-management/', views.menu_page, {'page_name': 'unit-management'}, name='unit-management'),
    path('category-management/', views.menu_page, {'page_name': 'category-management'}, name='category-management'),
    path('variety-management/', views.menu_page, {'page_name': 'variety-management'}, name='variety-management'),
    path('query-export/', views.menu_page, {'page_name': 'query-export'}, name='query-export'),
    path('daily-report/', views.menu_page, {'page_name': 'daily-report'}, name='daily-report'),
    path('warning/', views.menu_page, {'page_name': 'warning'}, name='warning'),
    path('approval/', views.menu_page, {'page_name': 'approval'}, name='approval'),
    path('attendance-staff/', views.menu_page, {'page_name': 'attendance-staff'}, name='attendance-staff'),
    path('outbound-staff/', views.menu_page, {'page_name': 'outbound-staff'}, name='outbound-staff'),
    path('outbound/', views.outbound_page, name='outbound'),
    path('api/outbound/varieties/', views.api_outbound_varieties, name='api-outbound-varieties'),
    path('api/outbound/variety-stock/<int:variety_id>/', views.api_outbound_variety_stock, name='api-outbound-variety-stock'),
    path('api/outbound/create/', views.api_outbound_create, name='api-outbound-create'),
    path('api/outbound/list/', views.api_outbound_list, name='api-outbound-list'),
    path('api/outbound/export-csv/', views.api_outbound_export_csv, name='api-outbound-export-csv'),
    path('inventory/', views.inventory_page, name='inventory'),
    path('api/inventory/overview/', views.api_inventory_overview, name='api-inventory-overview'),
    path('api/inventory/list/', views.api_inventory_list, name='api-inventory-list'),
    path('api/inventory/flow/<int:variety_id>/', views.api_inventory_flow, name='api-inventory-flow'),
]
